project_id = "zuljmldniwynmnilnffu"

[functions.process-meeting]
verify_jwt = false

[functions.send-slack-message]
verify_jwt = false

[functions.sync-google-calendar]
verify_jwt = false

[functions.google-oauth-callback]
verify_jwt = false

[functions.get-google-client-id]
verify_jwt = false