project_id = "zuljmldniwynmnilnffu"

[functions.process-meeting]
verify_jwt = false

[functions.send-slack-message]
verify_jwt = false

[functions.sync-google-calendar]
verify_jwt = false

[functions.google-oauth-callback]
verify_jwt = false

[functions.get-google-client-id]
verify_jwt = false

[functions.google-oauth-start]
verify_jwt = false

[functions.google-oauth-redirect]
verify_jwt = false

[functions.disconnect-google]
verify_jwt = false

[functions.test-slack-connection]
verify_jwt = false

[functions.notion-oauth-start]
verify_jwt = false

[functions.notion-oauth-callback]
verify_jwt = false

[functions.sync-notion]
verify_jwt = false

[functions.upload-recording]
verify_jwt = false

[functions.send-meeting-email]
verify_jwt = false
