import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const supabaseClient = createClient(
  Deno.env.get('SUPABASE_URL')!,
  Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
)

const RESEND_API_KEY = Deno.env.get('RESEND_API_KEY')

interface EmailReportRequest {
  meeting_id: string
  user_id: string
  recipient_email: string
  include_transcript?: boolean
}

function generateEmailHTML(insights: any, meeting: any): string {
  const summary = insights.summary_short || ''
  const keyPoints = Array.isArray(insights.key_points) ? insights.key_points.slice(0, 5) : []
  const decisions = Array.isArray(insights.decisions) ? insights.decisions.slice(0, 3) : []
  const actionItems = Array.isArray(insights.action_items) ? insights.action_items.slice(0, 5) : []

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #333; line-height: 1.6; }
    .container { max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: linear-gradient(135deg, #F97316, #F59E0B); padding: 30px; border-radius: 8px; color: white; margin-bottom: 30px; }
    .header h1 { margin: 0; font-size: 24px; }
    .header p { margin: 5px 0 0 0; opacity: 0.9; }
    .section { margin-bottom: 25px; }
    .section-title { font-size: 16px; font-weight: 600; color: #1C1917; margin-bottom: 12px; border-bottom: 2px solid #F97316; padding-bottom: 8px; }
    .summary { background: #FFF7ED; padding: 15px; border-radius: 6px; border-left: 4px solid #F97316; }
    .summary p { margin: 0; color: #333; }
    ul { margin: 0; padding-left: 20px; }
    li { margin-bottom: 8px; }
    .action-item { background: #f5f5f5; padding: 12px; border-radius: 4px; margin-bottom: 8px; }
    .action-item strong { color: #F97316; }
    .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; color: #999; font-size: 12px; }
    .badge { display: inline-block; background: #F97316; color: white; padding: 4px 8px; border-radius: 3px; font-size: 12px; margin-right: 5px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>📋 ${meeting.title}</h1>
      <p>${new Date(meeting.start_time).toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' })}</p>
    </div>

    ${summary ? `
    <div class="section">
      <div class="section-title">Executive Summary</div>
      <div class="summary">
        <p>${summary}</p>
      </div>
    </div>
    ` : ''}

    ${keyPoints.length > 0 ? `
    <div class="section">
      <div class="section-title">🎯 Key Points</div>
      <ul>
        ${keyPoints.map(point => `<li>${point}</li>`).join('')}
      </ul>
    </div>
    ` : ''}

    ${decisions.length > 0 ? `
    <div class="section">
      <div class="section-title">✅ Key Decisions</div>
      <ul>
        ${decisions.map(d => `<li>${d}</li>`).join('')}
      </ul>
    </div>
    ` : ''}

    ${actionItems.length > 0 ? `
    <div class="section">
      <div class="section-title">📌 Action Items</div>
      ${actionItems.map((item, i) => {
        const task = typeof item === 'string' ? item : item.task || ''
        const owner = typeof item === 'object' && item.owner ? item.owner : null
        const priority = typeof item === 'object' && item.priority ? item.priority : null
        return `
        <div class="action-item">
          <strong>${i + 1}. ${task}</strong>
          ${owner ? `<br><small style="color: #666;">Owner: ${owner}</small>` : ''}
          ${priority ? `<br><span class="badge">${priority}</span>` : ''}
        </div>
        `
      }).join('')}
    </div>
    ` : ''}

    <div class="footer">
      <p>Generated by EchoBrief • ${new Date().toLocaleDateString()}</p>
      <p style="margin-top: 10px;"><a href="https://echobrief-ten.vercel.app" style="color: #F97316; text-decoration: none;">View full report →</a></p>
    </div>
  </div>
</body>
</html>
`.trim()
}

async function sendViaResend(
  to: string,
  subject: string,
  html: string
): Promise<{ success: boolean; messageId?: string; error?: string }> {
  if (!RESEND_API_KEY) {
    throw new Error('RESEND_API_KEY not configured')
  }

  const response = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${RESEND_API_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      from: 'EchoBrief <noreply@oltaflock.ai>',
      to,
      subject,
      html,
    }),
  })

  if (!response.ok) {
    const error = await response.text()
    throw new Error(`Resend API error: ${response.status} ${error}`)
  }

  const data = await response.json()
  return {
    success: true,
    messageId: data.id,
  }
}

serve(async (req) => {
  if (req.method !== 'POST') {
    return new Response('Method not allowed', { status: 405 })
  }

  try {
    const {
      meeting_id,
      user_id,
      recipient_email,
      include_transcript = false,
    }: EmailReportRequest = await req.json()

    if (!meeting_id || !recipient_email) {
      return new Response(
        JSON.stringify({ error: 'Missing required fields: meeting_id, recipient_email' }),
        { status: 400 }
      )
    }

    console.log(`Sending email report for meeting ${meeting_id} to ${recipient_email}`)

    // Fetch meeting
    const { data: meeting, error: meetingError } = await supabaseClient
      .from('meetings')
      .select('*')
      .eq('id', meeting_id)
      .single()

    if (meetingError || !meeting) {
      throw new Error('Meeting not found')
    }

    // Fetch insights
    const { data: insights, error: insightsError } = await supabaseClient
      .from('meeting_insights')
      .select('*')
      .eq('meeting_id', meeting_id)
      .single()

    if (insightsError || !insights) {
      throw new Error('No insights found for this meeting')
    }

    // Generate HTML
    const html = generateEmailHTML(insights, meeting)

    // Send via Resend
    const sendResult = await sendViaResend(
      recipient_email,
      `Meeting Report: ${meeting.title}`,
      html
    )

    if (!sendResult.success) {
      throw new Error(sendResult.error || 'Failed to send email')
    }

    console.log(`Email sent to ${recipient_email}, message ID: ${sendResult.messageId}`)

    // Log email delivery
    const { error: logError } = await supabaseClient
      .from('email_messages')
      .insert({
        meeting_id,
        recipient_email,
        subject: `Meeting Report: ${meeting.title}`,
        status: 'sent',
        message_id: sendResult.messageId,
        sent_at: new Date().toISOString(),
      })

    if (logError) {
      console.warn('Failed to log email delivery:', logError.message)
      // Don't fail the request, email was already sent
    }

    return new Response(
      JSON.stringify({
        success: true,
        meeting_id,
        recipient_email,
        message_id: sendResult.messageId,
      }),
      { status: 200, headers: { 'Content-Type': 'application/json' } }
    )
  } catch (error: any) {
    console.error('Email report error:', error.message)

    // Log failed delivery attempt
    if (meeting_id && recipient_email) {
      try {
        await supabaseClient
          .from('email_messages')
          .insert({
            meeting_id,
            recipient_email,
            subject: `Meeting Report: [Error]`,
            status: 'failed',
            error_message: error.message,
          })
      } catch (logError) {
        console.warn('Failed to log email error:', logError)
      }
    }

    return new Response(
      JSON.stringify({
        error: error.message,
        success: false,
      }),
      { status: 500, headers: { 'Content-Type': 'application/json' } }
    )
  }
})
